// ==============================|| APPS REDUCER - ACTIONS ||============================== //

export const FETCH_APPS = '@apps/FETCH_APPS';
export const FETCH_APPS_SUCCESS = '@apps/FETCH_APPS_SUCCESS';
export const FETCH_APPS_FAILURE = '@apps/FETCH_APPS_FAILURE';

export const FETCH_TRASHED_APPS = '@apps/FETCH_TRASHED_APPS';
export const FETCH_TRASHED_APPS_SUCCESS = '@apps/FETCH_TRASHED_APPS_SUCCESS';
export const FETCH_TRASHED_APPS_FAILURE = '@apps/FETCH_TRASHED_APPS_FAILURE';

export const CREATE_APP = '@apps/CREATE_APP';
export const CREATE_APP_SUCCESS = '@apps/CREATE_APP_SUCCESS';
export const CREATE_APP_FAILURE = '@apps/CREATE_APP_FAILURE';

export const UPDATE_APP = '@apps/UPDATE_APP';
export const UPDATE_APP_SUCCESS = '@apps/UPDATE_APP_SUCCESS';
export const UPDATE_APP_FAILURE = '@apps/UPDATE_APP_FAILURE';

export const DELETE_APP = '@apps/DELETE_APP';
export const DELETE_APP_SUCCESS = '@apps/DELETE_APP_SUCCESS';
export const DELETE_APP_FAILURE = '@apps/DELETE_APP_FAILURE';

export const SOFT_DELETE_APP = '@apps/SOFT_DELETE_APP';
export const SOFT_DELETE_APP_OPTIMISTIC = '@apps/SOFT_DELETE_APP_OPTIMISTIC';
export const SOFT_DELETE_APP_SUCCESS = '@apps/SOFT_DELETE_APP_SUCCESS';
export const SOFT_DELETE_APP_FAILURE = '@apps/SOFT_DELETE_APP_FAILURE';
export const SOFT_DELETE_APP_ROLLBACK = '@apps/SOFT_DELETE_APP_ROLLBACK';

export const RECOVER_APP = '@apps/RECOVER_APP';
export const RECOVER_APP_OPTIMISTIC = '@apps/RECOVER_APP_OPTIMISTIC';
export const RECOVER_APP_SUCCESS = '@apps/RECOVER_APP_SUCCESS';
export const RECOVER_APP_FAILURE = '@apps/RECOVER_APP_FAILURE';
export const RECOVER_APP_ROLLBACK = '@apps/RECOVER_APP_ROLLBACK';

export const PERMANENT_DELETE_APP = '@apps/PERMANENT_DELETE_APP';
export const PERMANENT_DELETE_APP_OPTIMISTIC = '@apps/PERMANENT_DELETE_APP_OPTIMISTIC';
export const PERMANENT_DELETE_APP_SUCCESS = '@apps/PERMANENT_DELETE_APP_SUCCESS';
export const PERMANENT_DELETE_APP_FAILURE = '@apps/PERMANENT_DELETE_APP_FAILURE';
export const PERMANENT_DELETE_APP_ROLLBACK = '@apps/PERMANENT_DELETE_APP_ROLLBACK';

export const UPDATE_APP_FROM_SYNC = '@apps/UPDATE_APP_FROM_SYNC';

export const SET_SELECTED_APP = '@apps/SET_SELECTED_APP';
export const CLEAR_SELECTED_APP = '@apps/CLEAR_SELECTED_APP';

export const SET_MODAL_STATE = '@apps/SET_MODAL_STATE';
export const SET_LOADING_STATE = '@apps/SET_LOADING_STATE';

export const UPDATE_PROGRESS = '@apps/UPDATE_PROGRESS';
export const CLEAR_PROGRESS = '@apps/CLEAR_PROGRESS';
export const SET_CURRENT_PROGRESS_ID = '@apps/SET_CURRENT_PROGRESS_ID';
export const CLEAR_CURRENT_PROGRESS_ID = '@apps/CLEAR_CURRENT_PROGRESS_ID';

export const CLEAR_ALL_APPS_DATA = '@apps/CLEAR_ALL_APPS_DATA';

export const ADD_PENDING_OPERATION = '@apps/ADD_PENDING_OPERATION';
export const REMOVE_PENDING_OPERATION = '@apps/REMOVE_PENDING_OPERATION';
export const UPDATE_PENDING_OPERATION = '@apps/UPDATE_PENDING_OPERATION';

export const SHOW_PENDING_OPERATIONS_DIALOG = '@apps/SHOW_PENDING_OPERATIONS_DIALOG';
export const HIDE_PENDING_OPERATIONS_DIALOG = '@apps/HIDE_PENDING_OPERATIONS_DIALOG';
export const SET_CANCELLING_OPERATIONS = '@apps/SET_CANCELLING_OPERATIONS';
